services:
  - type: web
    name: blog-web
    env: node
    region: oregon
    plan: free
    buildCommand: cd ../.. && npm install -g pnpm && pnpm install && pnpm turbo run build --filter=@repo/web
    startCommand: cd apps/web && node .next/standalone/apps/web/server.js
    rootDir: apps/web
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString
      - key: JWT_SECRET
        sync: false

  - type: web
    name: blog-admin
    env: node
    region: oregon
    plan: free
    buildCommand: cd ../.. && npm install -g pnpm && pnpm install && pnpm turbo run build --filter=@repo/admin
    startCommand: cd apps/admin && node .next/standalone/apps/admin/server.js
    rootDir: apps/admin
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString
      - key: JWT_SECRET
        sync: false

databases:
  - name: blog-db
    plan: free
    region: oregon
    postgresMajorVersion: 15
